<?php

namespace common\models;

use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property string $name_uz
 * @property string $name_ru
 * @property string $name_en
 * @property string $filename
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Product[] $products
 */
class Category extends ActiveRecord
{


    /**
     * {@inheritdoc}
     */
    public static function tableName(): string
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_at'], 'default', 'value' => time()],
            [['updated_at'], 'default', 'value' => time()],
            [['name_uz', 'name_ru', 'name_en', 'filename'], 'required'],
            [['created_at', 'updated_at'], 'integer'],
            [['name_uz', 'name_ru', 'name_en', 'filename'], 'string', 'max' => 100],
        ];
    }

    public function beforeSave($insert): bool
    {
        if (!$this->isNewRecord){
            $this->updated_at = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels(): array
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name_uz' => Yii::t('app', 'Name Uz'),
            'name_ru' => Yii::t('app', 'Name Ru'),
            'name_en' => Yii::t('app', 'Name En'),
            'filename' => Yii::t('app', 'Filename'),
            'created_at' => Yii::t('app', 'Created at'),
            'updated_at' => Yii::t('app', 'Updated at'),
        ];
    }

    /**
     * Gets query for [[Products]].
     *
     * @return ActiveQuery
     */
    public function getProducts(): ActiveQuery
    {
        return $this->hasMany(Product::class, ['category_id' => 'id']);
    }

    public static function getList(): array
    {
        return ArrayHelper::map(self::find()->all(), 'id', 'name_uz');
    }

}
